package com.constantcontact.components.emailcampaigns;

import java.io.Serializable;

import com.constantcontact.components.Component;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a single Tracking Summary from {@link EmailCampaignBase} for the Email Campaign Service in Constant Contact.<br/>
 * This is expected in a response and should never be sent in a request - since this contains statistical data generated by the server.<br/>
 * It is actually hidden in {@link EmailCampaignRequest}.
 * 
 * @author ConstantContact
 */
public class TrackingSummary extends Component implements Serializable {

	/**
	 * Serial version unique identifier.
	 */
	private static final long serialVersionUID = -8897362333823015977L;

	@JsonIgnore
	private int sends;
	@JsonIgnore
	private int opens;
	@JsonIgnore
	private int clicks;
	@JsonIgnore
	private int forwards;
	@JsonIgnore
	private int unsubscribes;
	@JsonIgnore
	private int bounces;

	/**
	 * Get the Sends
	 * 
	 * @return The Sends
	 */
	@JsonProperty("sends")
	public int getSends() {
		return sends;
	}

	/**
	 * Get the Opens
	 * 
	 * @return The Opens
	 */
	@JsonProperty("opens")
	public int getOpens() {
		return opens;
	}

	/**
	 * Get the Clicks
	 * 
	 * @return The Clicks
	 */
	@JsonProperty("clicks")
	public int getClicks() {
		return clicks;
	}

	/**
	 * Get the Forwards
	 * 
	 * @return The Forwards
	 */
	@JsonProperty("forwards")
	public int getForwards() {
		return forwards;
	}

	/**
	 * Get the Unsubscribes
	 * 
	 * @return The Unsubscribes
	 */
	@JsonProperty("unsubscribes")
	public int getUnsubscribes() {
		return unsubscribes;
	}

	/**
	 * Get the Bounces
	 * 
	 * @return The bounces.
	 */
	@JsonProperty("bounces")
	public int getBounces() {
		return bounces;
	}

	/**
	 * Set the Sends
	 * 
	 * @param sends The Sends
	 */
	public void setSends(int sends) {
		this.sends = sends;
	}

	/**
	 * Set the Opens
	 * 
	 * @param opens The Opens
	 */
	public void setOpens(int opens) {
		this.opens = opens;
	}

	/**
	 * Set the Clicks
	 * 
	 * @param clicks The Clicks
	 */
	public void setClicks(int clicks) {
		this.clicks = clicks;
	}

	/**
	 * Set the Forwards
	 * 
	 * @param forwards The Forwards
	 */
	public void setForwards(int forwards) {
		this.forwards = forwards;
	}

	/**
	 * Set the Unsubscribes
	 * 
	 * @param unsubscribes The Unsubscribes
	 */
	public void setUnsubscribes(int unsubscribes) {
		this.unsubscribes = unsubscribes;
	}

	/**
	 * Set the Bounces
	 * 
	 * @param bounces The Bounces
	 */
	public void setBounces(int bounces) {
		this.bounces = bounces;
	}

	/**
	 * Default constructor.
	 */
	public TrackingSummary() {
		super();
	}

	/**
	 * Custom implementation for {@link Object#toString()}.
	 */
	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("TrackingSummary [sends=");
		builder.append(sends);
		builder.append(", opens=");
		builder.append(opens);
		builder.append(", clicks=");
		builder.append(clicks);
		builder.append(", forwards=");
		builder.append(forwards);
		builder.append(", unsubscribes=");
		builder.append(unsubscribes);
		builder.append(", bounces=");
		builder.append(bounces);
		builder.append("]");
		return builder.toString();
	}
}
